run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 10
